[package]
name = "enigma_rust"
version = "0.1.0"
authors = ["Meowcolm024 <luoyicong1026@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
